backend: 
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections: 
  - name: 'collection'
    label: 'Collection'
    folder: 'src/pages/collection'
    create: true
    identifier_field: name
    fields: 
      - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'collection'}
      - {label: 'Title', name: 'title', widget: 'text'}
      - {label: 'Description', name: 'description', widget: 'text'}
      - {label: 'Date', name: 'date', widget: 'date'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
      - {label: 'Keywords', name: 'keywords', widget: 'string'}

  - name: 'pages'
    label: 'Pages'
    files: 
      - file: 'src/pages/index.md'
        label: 'Home Page'
        name: 'index'
        fields: 
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page'}
          - {label: 'Heading', name: 'heading', widget: 'string'}
          - {label: 'Subheading', name: 'subheading', widget: 'string'}
          - {label: 'Hero Text', name: 'herotext', widget: 'string'}
          - {label: 'Keywords', name: 'keywords', widget: 'string'}